// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	patients "digimer-api/src/app/patients"

	mock "github.com/stretchr/testify/mock"
)

// Repositories is an autogenerated mock type for the Repositories type
type Repositories struct {
	mock.Mock
}

// CountDataByID provides a mock function with given fields: id
func (_m *Repositories) CountDataByID(id string) int {
	ret := _m.Called(id)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: id
func (_m *Repositories) DeleteByID(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertData provides a mock function with given fields: domain
func (_m *Repositories) InsertData(domain patients.Domain) error {
	ret := _m.Called(domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(patients.Domain) error); ok {
		r0 = rf(domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LookupLatestMRBookNumber provides a mock function with given fields:
func (_m *Repositories) LookupLatestMRBookNumber() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SelectAllData provides a mock function with given fields:
func (_m *Repositories) SelectAllData() ([]patients.Domain, error) {
	ret := _m.Called()

	var r0 []patients.Domain
	if rf, ok := ret.Get(0).(func() []patients.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]patients.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectDataByID provides a mock function with given fields: id
func (_m *Repositories) SelectDataByID(id string) (patients.Domain, error) {
	ret := _m.Called(id)

	var r0 patients.Domain
	if rf, ok := ret.Get(0).(func(string) patients.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(patients.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectDataByMRBookNumber provides a mock function with given fields: mrBookNumber
func (_m *Repositories) SelectDataByMRBookNumber(mrBookNumber string) (patients.Domain, error) {
	ret := _m.Called(mrBookNumber)

	var r0 patients.Domain
	if rf, ok := ret.Get(0).(func(string) patients.Domain); ok {
		r0 = rf(mrBookNumber)
	} else {
		r0 = ret.Get(0).(patients.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(mrBookNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: id, domain
func (_m *Repositories) UpdateByID(id string, domain patients.Domain) error {
	ret := _m.Called(id, domain)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, patients.Domain) error); ok {
		r0 = rf(id, domain)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
